import re

sentence = "The sun has finally set down"
x = re.search("^The",sentence)
print(x)
y = re.search("^Y",sentence)
print(y)
z = re.search("f+",sentence)
print(z)
a = re.search("\AThe",sentence)
print(a)
b = re.search("s.*n",sentence)
print(b)
c = re.search("s.n",sentence)
print(c)
d = re.search("s=",sentence)
print(d)
e = re.search("\Asun",sentence)
print(e)
f = re.search("\d",sentence)
print(f)
g = re.search("sun",sentence)
print(g)
h = re.search("f.y",sentence)
print(h)
i = re.search("f.n",sentence)
print(i)
j = re.search("f.n*",sentence)
print(j)
k = re.search("l+",sentence)
print(k)
l = re.search("T.n",sentence)
print(l)
m = re.search("T.sun*",sentence)
print(m)
n = re.search("f?n",sentence)
print(n)

o = re.search("Can[a-z]", "Can you tell me what is wrong with my shadow")
print(o)
p = re.search("r[a-z]tailor", "The tailor was terrible")
print(p)

